[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = [
    "tailwindcss",
    "-i",
    "./styles/tailwind.css",
    "-o",
    "./styles/index.css"
]